version: '3'
name: reckoning-dev
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 8241:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.11-alpine
    ports:
      - 8242:6379
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
networks:
  default:
    name: reckoning-network
