openapi: 3.1.0
x-stoplight:
  id: nytj1xscxausi
info:
  title: schema-v1
  description: Reckoning Api Schema V1
  version: '1.0'
  contact:
    name: Marten Klitzke
    url: 'https://reckoning.me'
    email: info@reckoning.me
  license:
    name: MIT License
    url: 'https://github.com/reckoning/reckoning/blob/main/LICENSE'
tags:
  - name: customers
    description: Customers
  - name: projects
    description: Projects
  - name: sessions
    description: Sessions
  - name: users
    description: Users
servers:
  - url: 'http://reckoning.test/api/v1'
    description: development
  - url: 'https://reckoning.me/api/v1'
    description: live
paths:
  /me:
    get:
      summary: Current User Detail
      description: Current User Detail
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: get-me
      parameters: []
      security:
        - sessionCookie: []
  /sessions:
    post:
      summary: Create Session
      description: Create new Session
      tags:
        - sessions
      operationId: create-session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: |
            Successfully authenticated. The session ID is returned in a cookie named `RECKONING`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: RECKONING=abcde12345; Path=/; HttpOnly
    delete:
      summary: Destroy Session
      description: Destroy the current Session
      tags:
        - sessions
      operationId: delete-session
      responses:
        '200':
          description: OK
      security:
        - sessionCookie: []
  /customers:
    get:
      summary: Customers Index
      description: List of Customers
      tags:
        - customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
      operationId: get-customers
      security:
        - sessionCookie: []
  '/customers/:id':
    get:
      summary: Customer Detail
      description: Customer Detail
      tags:
        - customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      operationId: 'get-customers-:id'
      security:
        - sessionCookie: []
  /projects:
    get:
      summary: Projects Index
      description: List of Projects
      tags:
        - projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
      operationId: get-projects
      security:
        - sessionCookie: []
  '/projects/:id':
    get:
      summary: Project Detail
      description: Project Detail
      tags:
        - projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
      operationId: 'get-projects-:id'
      security:
        - sessionCookie: []
components:
  schemas:
    Customer:
      type: object
      x-examples:
        example-1:
          id: 4a1be11b-edc4-4747-bc04-13cd8737c979
          name: Sekeido
          createdAt: '2014-09-17T09:10:03.304+02:00'
          updatedAt: '2015-02-06T00:27:44.003+01:00'
          links:
            show:
              href: /api/v1/customers/4a1be11b-edc4-4747-bc04-13cd8737c979
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        links:
          type: object
          properties:
            show:
              type: object
              properties:
                href:
                  type: string
                  format: uri
    Project:
      type: object
      x-examples:
        example-1:
          id: 406bec9a-dacb-4ddd-95a1-1222f2a8e010
          name: Core Team 2022
          customerName: Shipcloud GmbH
          label: Shipcloud GmbH - Core Team 2022
          tasks: []
          createdAt: '2022-09-08T21:49:49.479+02:00'
          updatedAt: '2022-09-08T21:50:46.004+02:00'
          links:
            show:
              href: /api/v1/projects/406bec9a-dacb-4ddd-95a1-1222f2a8e010
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        customerName:
          type: string
        label:
          type: string
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        links:
          type: object
          properties:
            show:
              type: object
              properties:
                href:
                  type: string
                  format: uri
    Task:
      type: object
      x-examples:
        example-1:
          id: 01d0847c-9c3e-419a-a92e-571fc94ff38b
          name: Entwicklung
          label: Entwicklung (fakturierbar)
          billable: true
          projectId: f5a1ef41-eb72-4202-b74e-a5668263c925
          createdAt: '2015-02-09T00:20:32.125+01:00'
          updatedAt: '2022-09-09T16:06:17.766+02:00'
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        label:
          type: string
        billable:
          type: boolean
        projectId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    User:
      title: User
      x-stoplight:
        id: wgmsb4opo1nmq
      x-tags:
        - users
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
        avatar:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    sessionCookie:
      name: RECKONING
      type: apiKey
      in: cookie
      description: Session Cookie for Authentication
