production: &default
  database: <%= ENV["DB_NAME"] || 'reckoning' %>
  adapter: postgresql
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  user: <%= ENV["DB_USER"] || 'root' %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV["DB_POOL_SIZE"] %>

staging:
  <<: *default

ci:
  <<: *default

development:
  <<: *default
  database: reckoning_dev

test:
  <<: *default
  database: reckoning_test
