shared:
  name: Reckoning
  copyright_owner: <%= ENV["COPYRIGHT_OWNER"] || 'Marten Klitzke' %>

  domain: <%= ENV["DOMAIN"] || "localhost:#{ENV["PORT"] || 8240}" %>
  url: <%= ENV["APP_URL"] %>

  api_version: v1

  s3_space: reckoning
  s3_region: fra1
  s3_endpoint: https://fra1.digitaloceanspaces.com

  cable_endpoint: <%= ENV["CABLE_ENDPOINT"] || "ws://localhost:#{ENV["PORT"]}/cable" %>
  cable_channel_prefix: <%= ENV["CABLE_CHANNEL_PREFIX"] %>

  cookie_domain: <%= ENV["COOKIE_DOMAIN"] || :all %>
  cookie_prefix: <%= ENV["COOKIE_PREFIX"] || 'RECKONING' %>

  jwt_expiration: <%= 24.hours.to_i %>

  mailer_default_from: <%= ENV["MAILER_DEFAULT_FROM"] || 'noreply@reckoning.me' %>

  registration: false
  demo: false

development:
  url: http://reckoning.test
  domain: reckoning.test

  registration: true
  demo: true

test:
  url: http://reckoning.test
  domain: reckoning.test

  registration: true
  demo: false
