name: Brakeman Job

on:
  workflow_call:

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1
      - name: Run Brakeman
        run: bundle exec brakeman --no-pager --format plain --exit-on-warn
