name: Check

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  ruby-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1

  ruby-audit:
    needs: ruby-setup
    uses: ./.github/workflows/ruby-audit.job.yml
